### ISSUE TITLE
license

### ISSUE THREAD

**Issue by mmaulwurff** [Blue-Shadow/nchud#36]
Since the project is [discontinued](https://forum.zdoom.org/viewtopic.php?f=45&t=33079&start=495#p1191029) and will no longer be updated by the author, it would help to add a proper license just in case someone would like to step in, fork the project and continue the development.

**Comment by Blue-Shadow** [comment]
The license is "Do What You Want" :P. Sorry, I'm not into the license thing. People are free to do whatever they want with the stuff I create and share in the community. They don't even need to ask for my permission.
